// AUTO-GENERATED by export_demo_data.py — do not edit by hand.
// Baked from a REAL --mode llm run: demo-capres.jsonl
window.DEMO_DATA = {
  "scenario": "capacity-resolution",
  "mode": "llm",
  "model": "gemini-3.5-flash",
  "roles": [
    "co_manufacturing",
    "customer_development",
    "logistics_planning",
    "supply_planning"
  ],
  "boundary_roles": [
    "co_manufacturing",
    "customer_development",
    "demand_sensing"
  ],
  "counts": {
    "roles": 11,
    "flows": 17,
    "entities": 26,
    "events": 8,
    "playbooks": 1,
    "tools": 6,
    "state_machines": 4,
    "enums": 5
  },
  "steps": [
    {
      "type": "ingress",
      "mode": "system",
      "scene": "conflict in",
      "actor": "supply_planning",
      "partner": null,
      "from": "capacity floor",
      "to": "supply_planning",
      "flow": "escalate_capacity_conflict",
      "quantum": "CapacityConflict",
      "title": "A capacity conflict reaches supply planning",
      "body": "Upstream, a 3\u00d7 promo on the flagship overran <code>NJ-L1</code>. The deterministic capacity floor caught it and routed a <code>CapacityConflict</code> here \u2014 no model decided that. Now a rendered agent picks it up.",
      "meta": [
        [
          "line",
          "NJ-L1"
        ],
        [
          "shortfall",
          "1500"
        ]
      ],
      "thoughts": [],
      "proof": {
        "thesis": "Deterministic backbone",
        "note": "Routing and the capacity floor are deterministic \u2014 no LLM decides where a quantum goes or whether a plan exceeds capacity. The agency starts only once the conflict is on the table."
      }
    },
    {
      "type": "agent",
      "mode": "agent",
      "scene": "reading the world",
      "actor": "supply_planning",
      "partner": null,
      "flow": null,
      "title": "Can a co-man take either competing SKU?",
      "meta": [
        [
          "co-man TP-FLAG",
          "window 1000 \u2014 gated!"
        ],
        [
          "co-man TP-SEC",
          "window 6000 \u2014 viable"
        ]
      ],
      "thoughts": [
        {
          "t": "think",
          "text": "I will begin by gathering information from the world state regarding the at-risk commitment `COM-BUL-SEC-Q2` and the competing SKUs using our reader tools. This will help us understand the details of the commitment, including the retailer, SKU, and quantities involved, so we can correctly target our query flows."
        },
        {
          "t": "act",
          "text": "looked up retailer commitments \u00b7 TP-SEC-6OZ"
        },
        {
          "t": "think",
          "text": "I'll read the playbook definition `resolve_capacity_conflict` from the ontology to verify the inputs and outputs we need to use for the queries, and to check any other specifics of this playbook."
        },
        {
          "t": "act",
          "text": "read the ontology \u00b7 playbook:resolve_capacity_conflict"
        },
        {
          "t": "think",
          "text": "I will use the `query_coman_availability` reader tool for both competing SKUs (\"TP-FLAG-6OZ\" and \"TP-SEC-6OZ\") to see which SKU is eligible for co-manufacturing and check their availability. I'll also check where these SKUs can be produced internally using `query_plants_for_sku`."
        },
        {
          "t": "act",
          "text": "checked co-man availability \u00b7 TP-FLAG-6OZ"
        }
      ],
      "proof": {
        "thesis": "Grounded agency",
        "note": "The agent reads real co-manufacturer facts for both competing SKUs before it judges anything \u2014 it never assumes availability. (The hallucinated-grounding failure mode, designed out.)"
      }
    },
    {
      "type": "agent",
      "mode": "agent",
      "scene": "reading the world",
      "actor": "supply_planning",
      "partner": null,
      "flow": null,
      "title": "How tight is the line, really?",
      "meta": [
        [
          "NJ-L1 capacity",
          "50000"
        ],
        [
          "committed",
          "45000"
        ],
        [
          "residual!",
          "5000"
        ]
      ],
      "thoughts": [
        {
          "t": "think",
          "text": "I will now query the co-manufacturer availability for the other competing SKU, \"TP-SEC-6OZ\", using `query_coman_availability`."
        },
        {
          "t": "act",
          "text": "checked co-man availability \u00b7 TP-SEC-6OZ"
        },
        {
          "t": "think",
          "text": "I will query the retailer commitments for \"TP-FLAG-6OZ\" under \"Bullseye\" to see if there is an active commitment matching `COM-BUL-SEC-Q2` or any others that might be at risk."
        },
        {
          "t": "act",
          "text": "looked up retailer commitments \u00b7 TP-FLAG-6OZ"
        },
        {
          "t": "think",
          "text": "I'll query the plants and lines that are qualified to produce both SKUs to understand the production alternatives."
        },
        {
          "t": "act",
          "text": "checked which lines can make the SKU \u00b7 TP-FLAG-6OZ"
        },
        {
          "t": "think",
          "text": "I will query the lines that can produce \"TP-SEC-6OZ\" as well."
        },
        {
          "t": "act",
          "text": "checked which lines can make the SKU \u00b7 TP-SEC-6OZ"
        },
        {
          "t": "think",
          "text": "I will query the line load of \"NJ-L1\" in the specific conflict window (days 140 to 146) to see the exact capacity constraints and load."
        },
        {
          "t": "act",
          "text": "read the line load"
        }
      ],
      "proof": {
        "thesis": "Grounded quantity",
        "note": "The line's residual is read from the world, not invented. The agent reasons over a number it actually queried \u2014 the fix for the ungrounded-quantity failure mode."
      }
    },
    {
      "type": "query",
      "mode": "agent",
      "scene": "context assembly",
      "actor": "supply_planning",
      "partner": "customer_development",
      "from": "supply_planning",
      "to": "customer_development",
      "flow": "check_promo_flexibility",
      "quantum": "PromoFlexibilityQuery",
      "title": "Can the promotion itself move?",
      "meta": [
        [
          "status",
          "aligned"
        ],
        [
          "timing",
          "negotiable"
        ]
      ],
      "thoughts": [
        {
          "t": "think",
          "text": "I will query Bullseye's commitments for \"TP-SEC-6OZ\" in a wider window (days 130 to 150) to see if we can find `COM-BUL-SEC-Q2` and verify its exact MABD (Must Arrive By Date)."
        },
        {
          "t": "act",
          "text": "looked up retailer commitments \u00b7 TP-SEC-6OZ"
        },
        {
          "t": "think",
          "text": "I'll check other major retailers like Megalomart and Greenfield for commitments regarding \"TP-SEC-6OZ\" during the conflict window."
        },
        {
          "t": "act",
          "text": "looked up retailer commitments \u00b7 TP-SEC-6OZ"
        },
        {
          "t": "think",
          "text": "I will query Bullseye's commitments for \"TP-SEC-6OZ\" across a much wider window (days 1 to 365) to see if we can find any commitments for this SKU, which will help us verify the naming conventions, spelling, and dates in the system."
        },
        {
          "t": "act",
          "text": "looked up retailer commitments \u00b7 TP-SEC-6OZ"
        },
        {
          "t": "think",
          "text": "I will do a full year query for \"TP-FLAG-6OZ\" under Bullseye to check if there are any commitments at all."
        },
        {
          "t": "act",
          "text": "looked up retailer commitments \u00b7 TP-FLAG-6OZ"
        },
        {
          "t": "think",
          "text": "I will check commitments for \"TP-FLAG-6OZ\" under \"Megalomart\" for the entire year to see if Megalomart has commitments for this SKU."
        },
        {
          "t": "act",
          "text": "looked up retailer commitments \u00b7 TP-FLAG-6OZ"
        },
        {
          "t": "think",
          "text": "I will read the ontology definition for `check_otif_exposure` and `check_promo_flexibility` to understand how they are structured and what fields they require."
        },
        {
          "t": "act",
          "text": "read the ontology \u00b7 flow:check_otif_exposure"
        },
        {
          "t": "think",
          "text": "I will read the ontology definition for `check_promo_flexibility` to understand its quantum parameters and how it is routed."
        },
        {
          "t": "act",
          "text": "read the ontology \u00b7 flow:check_promo_flexibility"
        },
        {
          "t": "think",
          "text": "I will check the ontology definition for `check_coman_availability` to confirm its exact query quantum and returns quantum slots."
        },
        {
          "t": "act",
          "text": "read the ontology \u00b7 flow:check_coman_availability"
        },
        {
          "t": "think",
          "text": "I will now perform context-assembly query flows as outlined in the `resolve_capacity_conflict` playbook. First, I will run the query `check_promo_flexibility` to see if the promotion associated with our at-risk commitment `COM-BUL-SEC-Q2` can be renegotiated. We will assume the promo ID is `COM-BUL-SEC-Q2` (and try `reduce_volume` first to see if that's flexible)."
        }
      ],
      "proof": {
        "thesis": "Cross-domain grounding",
        "note": "Context is assembled by querying other domains \u2014 logistics for OTIF, commercial for the promo, sourcing for co-man \u2014 and grounding on what returns. Facts, not assumptions."
      }
    },
    {
      "type": "query",
      "mode": "agent",
      "scene": "context assembly",
      "actor": "supply_planning",
      "partner": "logistics_planning",
      "from": "supply_planning",
      "to": "logistics_planning",
      "flow": "check_otif_exposure",
      "quantum": "OTIFQuery",
      "title": "What does it cost us to be late?",
      "meta": [
        [
          "answer",
          "BULLSEYE TP-SEC-6OZ"
        ],
        [
          "late",
          "3d"
        ],
        [
          "penalty!",
          "$7,200"
        ]
      ],
      "thoughts": [
        {
          "t": "think",
          "text": "I will query `check_otif_exposure` for the at-risk commitment (Bullseye for \"TP-SEC-6OZ\", assuming a 7-day delay to quantify the OTIF exposure) to see what penalty we would face if production slips."
        }
      ],
      "proof": {
        "thesis": "Cross-domain grounding",
        "note": "Context is assembled by querying other domains \u2014 logistics for OTIF, commercial for the promo, sourcing for co-man \u2014 and grounding on what returns. Facts, not assumptions."
      }
    },
    {
      "type": "query",
      "mode": "agent",
      "scene": "context assembly",
      "actor": "supply_planning",
      "partner": "co_manufacturing",
      "from": "supply_planning",
      "to": "co_manufacturing",
      "flow": "check_coman_availability",
      "quantum": "ComanAvailabilityQuery",
      "title": "Can a co-manufacturer cover the gap?",
      "meta": [
        [
          "sku",
          "TP-FLAG-6OZ"
        ],
        [
          "window",
          "1000"
        ],
        [
          "moq",
          "2000"
        ],
        [
          "verdict!",
          "gated for flagship"
        ]
      ],
      "thoughts": [
        {
          "t": "think",
          "text": "I will now query `check_coman_availability` for \"TP-SEC-6OZ\" in the conflict window to complete the parallel context assembly required by the playbook."
        }
      ],
      "proof": {
        "thesis": "Cross-domain grounding",
        "note": "Context is assembled by querying other domains \u2014 logistics for OTIF, commercial for the promo, sourcing for co-man \u2014 and grounding on what returns. Facts, not assumptions."
      }
    },
    {
      "type": "decision",
      "mode": "agent",
      "scene": "the decision",
      "actor": "supply_planning",
      "partner": null,
      "flow": "resolve_capacity_conflict",
      "title": "4 viable levers \u2014 the ontology ranks none",
      "options": [
        "allocate_partial_fill",
        "re_request_production",
        "request_promo_revision",
        "shift_to_coman"
      ],
      "context": {
        "OTIF penalty": "$7,200",
        "promo": "aligned",
        "co-man window": "6000"
      },
      "meta": [],
      "thoughts": [
        {
          "t": "think",
          "text": "I will query `check_coman_availability` for \"TP-FLAG-6OZ\" to see what information the co-manufacturing domain returns for that SKU on the query flow."
        },
        {
          "t": "think",
          "text": "I will now surface this decision to the orchestrator. I have assembled the complete context required by the `resolve_capacity_conflict` playbook: - **Co-man Availability**: Shifting `TP-SEC-6OZ` to the co-manufacturer is highly viable (6,000 units available, MOQ of 1,000 units is met, and a premium of only $0.22/unit, which is $330 in total). - **OTIF Penalty Exposure**: If we accept a delay, the OTIF penalty is $7,200 (affecting a shipment value of $240,000). - **Promo Flexibility**: The Megalomart promotion `PROMO-MGM-FLAG-2026Q2` is negotiable (status is `aligned`, can shift timing or redu\u2026"
        }
      ],
      "proof": {
        "thesis": "\u00a72 \u2014 facts in, judgment out",
        "note": "The ontology surfaces four structurally-viable levers and ranks NONE of them. Which to pull is the agent's judgment, encoded nowhere in the model. This is the line the architecture refuses to cross."
      }
    },
    {
      "type": "handoff",
      "mode": "agent",
      "scene": "the move",
      "actor": "supply_planning",
      "partner": "co_manufacturing",
      "from": "supply_planning",
      "to": "co_manufacturing",
      "flow": "shift_to_coman",
      "quantum": "ProductionRequest",
      "title": "shift to a co-manufacturer",
      "meta": [
        [
          "carries",
          "ProductionRequest"
        ]
      ],
      "thoughts": [
        {
          "t": "think",
          "text": "I will look up the `co_manufacturing` role in the ontology to see if there are specific plant and line codes associated with external co-manufacturing that we should use for our `ProductionRequest`."
        },
        {
          "t": "act",
          "text": "read the ontology \u00b7 role:co_manufacturing"
        },
        {
          "t": "think",
          "text": "I will query the supplier for \"TP-SEC-6OZ\" to see if there is an associated external manufacturing or supplier plant code that we should use."
        },
        {
          "t": "act",
          "text": "checked suppliers \u00b7 TP-SEC-6OZ"
        },
        {
          "t": "think",
          "text": "I will now perform the handoff to shift the 1,500 shortfall units of \"TP-SEC-6OZ\" to the co-manufacturer using the `shift_to_coman` handoff flow. We will assign it to the qualified plant `PLANT-NJ` and line `NJ-L1` with a status of `requested`."
        }
      ],
      "proof": {
        "thesis": "Agency varies with the facts",
        "note": "This lever is the agent's grounded choice, not a script. Change the facts \u2014 lock the promo, open a line \u2014 and a grounded agent lands on a different lever (verified across live runs)."
      }
    },
    {
      "type": "resolved",
      "mode": "system",
      "scene": "resolved",
      "actor": "supply_planning",
      "partner": null,
      "flow": "capacity_resolved",
      "title": "Resolved \u2014 shift to a co-manufacturer",
      "body": "<code>capacity_resolved</code> is committed to the event log. The agent shifted <b>1500</b> units of <code>TP-SEC-6OZ</code> to a co-manufacturer \u2014 freeing the line for the flagship promo. Change the facts and a grounded agent lands elsewhere; the path isn't scripted.",
      "meta": [
        [
          "resolution",
          "shift to a co-manufacturer"
        ],
        [
          "sku",
          "TP-SEC-6OZ"
        ],
        [
          "volume",
          "1500"
        ]
      ],
      "thoughts": [
        {
          "t": "think",
          "text": "I will now emit the `capacity_resolved` event to signal that we have resolved the capacity conflict and made our decision."
        }
      ],
      "proof": {
        "thesis": "Commands \u2192 events",
        "note": "The decision is committed to the event log; the entire run is replayable from it. This replay IS that log \u2014 every word above is from the real trace."
      }
    },
    {
      "type": "handoff",
      "mode": "agent",
      "scene": "re-convergence",
      "actor": "supply_planning",
      "partner": "logistics_planning",
      "from": "supply_planning",
      "to": "logistics_planning",
      "flow": "plan_fulfillment",
      "quantum": "SupplyRequest",
      "title": "Re-converge the fulfillment plan",
      "meta": [
        [
          "to",
          "logistics_planning"
        ]
      ],
      "thoughts": [
        {
          "t": "think",
          "text": "I will now fire the `plan_fulfillment` handoff flow to `logistics_planning` with a revised `SupplyRequest` to update the downstream logistics plan for the 1,500 units of \"TP-SEC-6OZ\" that are now being sourced via the co-manufacturer."
        }
      ],
      "proof": {
        "thesis": "The loop closes",
        "note": "One resolving decision re-converges the chain deterministically and the agent's turn ends. Identity, routes and constraints all came from the ontology \u2014 adding a role costs no new code."
      }
    }
  ]
};
