// AUTO-GENERATED by export_demo_data.py — do not edit by hand.
// Baked from a REAL --mode llm run: demo-capres.jsonl
window.DEMO_DATA = {
  "scenario": "capacity-resolution",
  "mode": "llm",
  "model": "gemini-3.5-flash",
  "roles": [
    "co_manufacturing",
    "customer_development",
    "logistics_planning",
    "supply_planning"
  ],
  "boundary_roles": [
    "co_manufacturing",
    "customer_development",
    "demand_sensing"
  ],
  "counts": {
    "roles": 11,
    "flows": 17,
    "entities": 26,
    "events": 8,
    "playbooks": 1,
    "tools": 6,
    "state_machines": 4,
    "enums": 5
  },
  "steps": [
    {
      "type": "ingress",
      "mode": "system",
      "scene": "conflict in",
      "actor": "supply_planning",
      "partner": null,
      "from": "capacity floor",
      "to": "supply_planning",
      "flow": "escalate_capacity_conflict",
      "quantum": "CapacityConflict",
      "title": "A capacity conflict reaches supply planning",
      "body": "Upstream, a 3\u00d7 promo on the flagship overran <code>NJ-L1</code>. The deterministic capacity floor caught it and routed a <code>CapacityConflict</code> here \u2014 no model decided that. Now a rendered agent picks it up.",
      "meta": [
        [
          "line",
          "NJ-L1"
        ],
        [
          "shortfall",
          "1500"
        ]
      ]
    },
    {
      "type": "agent",
      "mode": "agent",
      "scene": "reading the world",
      "actor": "supply_planning",
      "partner": null,
      "flow": null,
      "title": "Can a co-man take either competing SKU?",
      "reasoning": "I will use the `query_coman_availability` reader tool for both competing SKUs (\"TP-FLAG-6OZ\" and \"TP-SEC-6OZ\") to see which SKU is eligible for co-manufacturing and check their availability. I'll also check where these SKUs can be produced internally using `query_plants_for_sku`.",
      "meta": [
        [
          "co-man TP-FLAG",
          "window 1000 < 1500 \u2014 gated!"
        ],
        [
          "co-man TP-SEC",
          "window 6000 \u2265 1500 \u2014 viable"
        ]
      ]
    },
    {
      "type": "agent",
      "mode": "agent",
      "scene": "reading the world",
      "actor": "supply_planning",
      "partner": null,
      "flow": null,
      "title": "How tight is the line, really?",
      "reasoning": "I will query the line load of \"NJ-L1\" in the specific conflict window (days 140 to 146) to see the exact capacity constraints and load.",
      "meta": [
        [
          "NJ-L1 capacity",
          "50000"
        ],
        [
          "committed",
          "45000"
        ],
        [
          "residual!",
          "5000"
        ]
      ]
    },
    {
      "type": "query",
      "mode": "agent",
      "scene": "context assembly",
      "actor": "supply_planning",
      "partner": "customer_development",
      "from": "supply_planning",
      "to": "customer_development",
      "flow": "check_promo_flexibility",
      "quantum": "PromoFlexibilityQuery",
      "title": "Can the promotion itself move?",
      "reasoning": "I will now perform context-assembly query flows as outlined in the `resolve_capacity_conflict` playbook. First, I will run the query `check_promo_flexibility` to see if the promotion associated with our at-risk commitment `COM-BUL-SEC-Q2` can be renegotiated. We will assume the promo ID is `COM-BUL-SEC-Q2` (and try `r\u2026",
      "meta": [
        [
          "status",
          "aligned"
        ],
        [
          "timing",
          "negotiable"
        ]
      ]
    },
    {
      "type": "query",
      "mode": "agent",
      "scene": "context assembly",
      "actor": "supply_planning",
      "partner": "logistics_planning",
      "from": "supply_planning",
      "to": "logistics_planning",
      "flow": "check_otif_exposure",
      "quantum": "OTIFQuery",
      "title": "What does it cost us to be late?",
      "reasoning": "I will query `check_otif_exposure` for the at-risk commitment (Bullseye for \"TP-SEC-6OZ\", assuming a 7-day delay to quantify the OTIF exposure) to see what penalty we would face if production slips.",
      "meta": [
        [
          "answer",
          "BULLSEYE TP-SEC-6OZ"
        ],
        [
          "late",
          "3d"
        ],
        [
          "penalty!",
          "$7,200"
        ]
      ]
    },
    {
      "type": "query",
      "mode": "agent",
      "scene": "context assembly",
      "actor": "supply_planning",
      "partner": "co_manufacturing",
      "from": "supply_planning",
      "to": "co_manufacturing",
      "flow": "check_coman_availability",
      "quantum": "ComanAvailabilityQuery",
      "title": "Can a co-manufacturer cover the gap?",
      "reasoning": "I will now query `check_coman_availability` for \"TP-SEC-6OZ\" in the conflict window to complete the parallel context assembly required by the playbook.",
      "meta": [
        [
          "sku",
          "TP-FLAG-6OZ"
        ],
        [
          "window",
          "1000"
        ],
        [
          "moq",
          "2000"
        ],
        [
          "verdict!",
          "gated for flagship"
        ]
      ]
    },
    {
      "type": "decision",
      "mode": "agent",
      "scene": "the decision",
      "actor": "supply_planning",
      "partner": null,
      "flow": "resolve_capacity_conflict",
      "title": "4 viable levers \u2014 the ontology ranks none",
      "reasoning": "I will now surface this decision to the orchestrator. I have assembled the complete context required by the `resolve_capacity_conflict` playbook: - **Co-man Availability**: Shifting `TP-SEC-6OZ` to the co-manufacturer is highly viable (6,000 units available, MOQ of 1,000 units is met, and a premium of only $0.22/unit, which is $330 in total). - **OTIF Penalty Exposure**: If we accept a delay, the OTIF penalty is $7,200 (affecting a shi\u2026",
      "options": [
        "allocate_partial_fill",
        "re_request_production",
        "request_promo_revision",
        "shift_to_coman"
      ],
      "context": {
        "OTIF penalty": "$7,200",
        "promo": "aligned",
        "co-man window": "6000"
      },
      "meta": []
    },
    {
      "type": "handoff",
      "mode": "agent",
      "scene": "the move",
      "actor": "supply_planning",
      "partner": "co_manufacturing",
      "from": "supply_planning",
      "to": "co_manufacturing",
      "flow": "shift_to_coman",
      "quantum": "ProductionRequest",
      "title": "shift to a co-manufacturer",
      "reasoning": "I will now perform the handoff to shift the 1,500 shortfall units of \"TP-SEC-6OZ\" to the co-manufacturer using the `shift_to_coman` handoff flow. We will assign it to the qualified plant `PLANT-NJ` and line `NJ-L1` with a status of `requested`.",
      "meta": [
        [
          "carries",
          "ProductionRequest"
        ]
      ]
    },
    {
      "type": "resolved",
      "mode": "system",
      "scene": "resolved",
      "actor": "supply_planning",
      "partner": null,
      "flow": "capacity_resolved",
      "title": "Resolved \u2014 shift to a co-manufacturer",
      "body": "<code>capacity_resolved</code> is committed to the event log. The agent shifted <b>1500</b> units of <code>TP-SEC-6OZ</code> to a co-manufacturer \u2014 freeing the line for the flagship promo. Change the facts and a grounded agent lands elsewhere; the path isn't scripted.",
      "meta": [
        [
          "resolution",
          "shift to a co-manufacturer"
        ],
        [
          "sku",
          "TP-SEC-6OZ"
        ],
        [
          "volume",
          "1500"
        ]
      ]
    },
    {
      "type": "handoff",
      "mode": "agent",
      "scene": "re-convergence",
      "actor": "supply_planning",
      "partner": "logistics_planning",
      "from": "supply_planning",
      "to": "logistics_planning",
      "flow": "plan_fulfillment",
      "quantum": "SupplyRequest",
      "title": "Re-converge the fulfillment plan",
      "reasoning": "I will now fire the `plan_fulfillment` handoff flow to `logistics_planning` with a revised `SupplyRequest` to update the downstream logistics plan for the 1,500 units of \"TP-SEC-6OZ\" that are now being sourced via the co-manufacturer.",
      "meta": [
        [
          "to",
          "logistics_planning"
        ]
      ]
    }
  ]
};
