"""Export the demo's data to a static `data.js` the UI loads as `window.DEMO_DATA`.

Bakes two things, from the *real* seams (no mocks, no API key — stub mode):

  • the agentic RUN  — a full-demo stub trace (Scene 1→6 event log): the answer to
    the CSCO's Q2 ("what is our agentic strategy"); and
  • the ontology IMPACT — `impact_analysis("TradePromotion", "slip_one_week")` +
    model summary + the resolution playbook + a couple of role views, from the 7-O
    knowledge service: the answer to Q1 ("what is an ontology, and is it legible").

Writing `window.DEMO_DATA = {...}` (rather than a fetched JSON) lets `index.html`
open straight from `file://` with zero server — the most robust shape for a live
demo or a recorded video.

Run:  uv run python demo_ui/export_demo_data.py
"""
from __future__ import annotations

import asyncio
import json
from pathlib import Path

from mcp_server.core import OntologyKnowledgeService

from e2e_orchestrator.runtime.main import build_scenario_orchestrator

HERE = Path(__file__).resolve().parent
SCENARIO = "full-demo"
IMPACT_START = "TradePromotion"
IMPACT_CHANGE = "slip_one_week"


def _trace() -> dict:
    """Run the full promo-whiplash narrative in stub mode and capture its event
    log (Scene 1→6). Mirrors how the DoD tests drive a scenario."""
    orch, backend, _service, spec = build_scenario_orchestrator(SCENARIO, mode="stub")
    asyncio.run(spec["seeder"](orch))
    events = backend.read_events()
    out = [
        {"seq": e.seq, "kind": e.kind, "idempotency_key": e.idempotency_key, "payload": e.payload}
        for e in events
    ]
    roles = sorted({e.payload.get("role") for e in events if e.kind == "agent_invocation_started"})
    return {"scenario": SCENARIO, "events": out, "roles": [r for r in roles if r]}


def _impact() -> dict:
    """The 7-O structural closure + the graph (nodes/edges derived from the impact
    paths) + model summary + the resolution playbook + role views."""
    k = OntologyKnowledgeService()
    imp = k.impact_analysis(IMPACT_START, change=IMPACT_CHANGE)
    summary = k.model_summary()
    playbook = k.read_playbook("resolve_capacity_conflict")

    # Build a node/edge graph for the blast-radius viz from the structural paths.
    # Each path is the shortest chain of edges start→node; their union is the
    # drawable graph. Depth = path length (the ring a node sits in).
    nodes: dict[str, dict] = {IMPACT_START: {"id": IMPACT_START, "kind": imp["start_kind"], "depth": 0}}
    edges: dict[tuple, dict] = {}
    for nid, path in imp["paths"].items():
        depth = len(path)
        kind = next((e["kind"] for e in path if e["id"] == nid), None)
        nodes.setdefault(nid, {"id": nid, "kind": kind, "depth": depth})
        if nodes[nid]["depth"] > depth:
            nodes[nid]["depth"] = depth
        for e in path:
            key = (e["from"], e["id"])
            edges.setdefault(key, {"source": e["from"], "target": e["id"], "relation": e["relation"]})

    return {
        "start": IMPACT_START,
        "change": IMPACT_CHANGE,
        "affected": imp["affected"],
        "affected_count": imp["affected_count"],
        "paths": imp["paths"],
        "note": imp["note"],
        "counts": summary["counts"],
        "boundary_roles": summary["boundary_roles"],
        "playbook": playbook,
        # The ontology-rendered identity for every affected role — click any role
        # in the blast radius to read the exact prompt the agent runs on (Q1: the
        # model is legible, and it IS the agent's identity).
        "roleviews": {r: k.roleview(r) for r in imp["affected"].get("role", [])},
        "graph": {"nodes": list(nodes.values()), "edges": list(edges.values())},
    }


def main() -> None:
    data = {"trace": _trace(), "impact": _impact()}
    payload = json.dumps(data, indent=2, default=str)
    out = HERE / "data.js"
    out.write_text(
        "// AUTO-GENERATED by export_demo_data.py — do not edit by hand.\n"
        "// Baked from the real orchestrator (stub trace) + 7-O knowledge service.\n"
        f"window.DEMO_DATA = {payload};\n",
        encoding="utf-8",
    )
    t, i = data["trace"], data["impact"]
    print(f"wrote {out.relative_to(HERE.parent)}")
    print(f"  trace:  {len(t['events'])} events, roles={t['roles']}")
    print(f"  impact: {i['affected_count']} affected, graph {len(i['graph']['nodes'])} nodes / {len(i['graph']['edges'])} edges")


if __name__ == "__main__":
    main()
